name: Acoular üëÅÔ∏è Organizational CI

on:
  pull_request:
    branches: [ master ]

jobs:
  conda:
    uses: acoular/ci/.github/workflows/conda.yml@main

  coverage:
    uses: acoular/ci/.github/workflows/coverage.yml@main
    permissions:
      pull-requests: write

  docs:
    uses: acoular/ci/.github/workflows/docs.yml@main

  github:
    uses: acoular/ci/.github/workflows/github.yml@main

  linting:
    uses: acoular/ci/.github/workflows/linting.yml@main

  pypi:
    uses: acoular/ci/.github/workflows/pypi.yml@main
    with:
      index: testpypi

  tests:
    uses: acoular/ci/.github/workflows/tests.yml@main
