name: "Manual: PyPI ğŸ“¦ Build ğŸ› ï¸ & Deploy"
run-name: Build Pkg ğŸ› ï¸ & Publish to ${{ case(inputs.index == 'pypi', 'PyPI', 'TestPyPI') }} ğŸ“¦
on:
  workflow_dispatch:
    inputs:
      index:
        description: 'The package index to publish to:'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  build_and_deploy:
    uses: acoular/ci/.github/workflows/pypi.yml@main
    with:
      index: ${{ inputs.index }}
      deploy: true
