name: Release CI ✴️
permissions:
  contents: read
on:
  release:
    types: [ published ]

jobs:
  conda:
    uses: acoular/ci/.github/workflows/conda.yml@main
    with:
      deploy: true

  docs:
    uses: acoular/ci/.github/workflows/docs.yml@main
    permissions:
      contents: write
    with:
      deploy: true

  pypi:
    uses: acoular/ci/.github/workflows/pypi.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      deploy: true
      index: pypi
